# Generated by Django 4.1 on 2022-08-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('sexo', models.TextField(max_length=2)),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familiares',
        ),
    ]
