# Generated by Django 4.1 on 2022-08-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_familiar_delete_familiares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='sexo',
            field=models.CharField(choices=[('m', 'masculino'), ('f', 'femenino')], max_length=1),
        ),
    ]
